--- 
title: "BIG DATA URBANA"
author: "Angie Scetta"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
subtitle: "Herramientas y Datos para conocer el Territorio"
lang: es
output:
  html_document:
    css: style.css
---

# INTRODUCCIÓN {-}

¡Hola a todos!

**¡Bienvenidos a BIG DATA URBANA!**

Estamos en un momento en que las Ciudades producen millones y millones de datos por segundo y hoy tenemos la posibilidad de aprovecharlos desde nuestra profesión para poder trabajar y tomar decisiones en base a evidencia real.

El objetivo del curso es presentar a los profesionales interesados en analizar diversas variables territoriales (sociodemográficas, mercado inmobiliario, actividad económica, transporte, movilidad, salud, educación, etc), la importancia de conocer herramientas analíticas que les permitan manipular y extraer conocimiento de grandes volúmenes de datos para tomar mejores decisiones a la hora de diagnosticar, comprender e intervenir el territorio.

El curso será práctico y se enseñarán los conocimientos básicos del lenguaje de programación R y del software libre RStudio, y su potencialidad para el análisis de datos urbanos.

A lo largo de 4 clases aplicaremos la herramienta a un ejemplo real, con el fin de analizar, describir, interpretar, visualizar y extraer conocimiento de datos existentes. El caso de estudio será el mercado inmobiliario en CABA y se utilizarán datos provenientes de fuentes públicas.

Será un curso de 4 clases de 3hs donde se estima un 90% práctico y un 10% teórico.

## PROGRAMA {-}

**Clase 1: CONOCER**

¿Qué es la Ciencia de Datos? ¿Cómo utilizar grandes volúmenes de datos para analizar dinámicas urbanas? ¿Qué datos existen? Introducción a programación en lenguaje R y el software RStudio.

Para esta clase será necesario tener previamente instalado el lenguaje de programación R (https://cloud.r-project.org/) , y la interfaz gráfica RStudio Desktop (https://rstudio.com/products/rstudio/download/).

**Clase 2: EXPLORAR**

¿Qué información contienen las bases de datos? ¿Cómo se estructuran?

Las funciones de *tidyverse* para manipular e interpretar los datos: Extraer información útil a partir de Seleccionar, Filtrar, Ordenar, Modificar y Resumir los datos.

**Clase 3: GRAFICAR**

¿Qué dicen los datos? ¿Cómo puedo facilitar la comprensión de la información?

Extraer conocimiento de los datos a partir de la visualización de los mismos. Comunicar resultados a partir de gráficos.

**Clase 4: MAPEAR**

¿Dónde se ubican los datos? ¿Cómo se distribuyen en el territorio? ¿Presentan algún patrón espacial?

Análisis espacial de los datos. Visualización a partir de mapas.